name: CI

on:
  push:
    branches:
      - main
  schedule:
    # build at 00:05 everyday
    - cron:  '5 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v2

    - name: Print emacs version
      run: emacs --version

    - name: Install dependency
      run: sudo apt-get install aspell aspell-en
  
    - name: Install eaf
      run: .emacs.d/site-lisp/emacs-application-framework --install-all-apps

    - name: Run tests
      run: make test
