name: CI

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '5 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v2

    - name: Print emacs version
      run: emacs --version

    - name: apt-get update
      run: sudo apt-get update
      
    - name: Install dependency
      run: sudo apt-get install aspell aspell-en

    - name: Install EAF denpendency
      run: sudo apt-get -y install python3-qtconsole python3-pyquery fd-find aria2 libtag1-dev python3-qrcode python3-markdown

    - name: Install EAF
      run: ~/work/emacs.d/emacs.d/site-lisp/emacs-application-framework/install-eaf.py --install-all-apps

    - name: Create org-roam directory
      run: mkdir ~/org-roam

    - name: Run tests
      run: make test